import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  list: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  item: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px',
    background: 'var(--color-elevated)',
    border: '1px solid var(--color-elevated-border)',
    borderRadius: 14,
    flexWrap: 'wrap',
    gap: 12,
  },
  emptyState: {
    padding: 18,
    borderRadius: 14,
    background: 'rgba(15, 23, 42, 0.44)',
    border: '1px dashed var(--color-elevated-border)',
  },
  emptyTitle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  },
  emptyText: {
    margin: '8px 0 0',
    color: 'var(--color-text-muted)',
    lineHeight: 1.5,
  },
  info: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    flex: 1,
    minWidth: 220,
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  project: {
    fontWeight: 600,
  },
  activeBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '4px 8px',
    borderRadius: 999,
    background: 'var(--color-accent-soft)',
    color: 'var(--color-text)',
    fontSize: 12,
    fontWeight: 700,
  },
  metaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  time: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 14,
    color: 'var(--color-text-muted)',
  },
  duration: {
    fontSize: 13,
    color: 'var(--color-text)',
    padding: '4px 8px',
    borderRadius: 999,
    background: 'var(--color-input-bg)',
  },
  description: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 14,
    color: 'var(--color-text-muted)',
    marginTop: 4,
  },
  inlineHint: {
    fontSize: 12,
    color: 'rgba(148, 163, 184, 0.82)',
  },
  commentInputWrap: {
    marginTop: 4,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  commentInput: {
    flex: 1,
    padding: 8,
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    background: 'var(--color-input-bg)',
    color: 'var(--color-text)',
    fontSize: 14,
  },
  actions: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
  editButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    background: 'transparent',
    color: 'var(--color-text-muted)',
    fontSize: 13,
    cursor: 'pointer',
  },
  deleteButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    borderRadius: 8,
    border: 'none',
    background: 'var(--color-danger-soft)',
    color: 'var(--color-danger-text)',
    fontSize: 13,
    cursor: 'pointer',
  },
  confirmDeleteButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    borderRadius: 8,
    border: 'none',
    background: 'var(--color-danger-strong)',
    color: 'white',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
  },
  editForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    width: '100%',
    padding: 4,
  },
  select: {
    padding: 8,
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    background: 'var(--color-input-bg)',
    color: 'var(--color-text)',
    fontSize: 14,
  },
  input: {
    padding: 8,
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    background: 'var(--color-input-bg)',
    color: 'var(--color-text)',
    fontSize: 14,
  },
  editActions: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
  saveButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 16px',
    borderRadius: 8,
    border: 'none',
    background: 'var(--color-success)',
    color: 'white',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: 14,
  },
  cancelButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 16px',
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    background: 'transparent',
    color: 'var(--color-text-muted)',
    cursor: 'pointer',
    fontSize: 14,
  },
}