import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  addForm: {
    display: 'flex',
    gap: 8,
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  input: {
    flex: 1,
    minWidth: 220,
    padding: 10,
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    background: 'var(--color-input-bg)',
    color: 'var(--color-text)',
    fontSize: 14,
  },
  addButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 16px',
    borderRadius: 8,
    border: 'none',
    background: 'var(--color-success)',
    color: 'white',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: 14,
  },
  helperText: {
    margin: '0 0 16px',
    color: 'rgba(148, 163, 184, 0.86)',
    fontSize: 14,
    lineHeight: 1.5,
  },
  emptyState: {
    padding: 18,
    marginBottom: 16,
    borderRadius: 14,
    background: 'rgba(15, 23, 42, 0.44)',
    border: '1px dashed var(--color-elevated-border)',
  },
  emptyTitle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  },
  emptyText: {
    margin: '8px 0 0',
    color: 'var(--color-text-muted)',
    lineHeight: 1.5,
  },
  list: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  item: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px',
    background: 'var(--color-elevated)',
    border: '1px solid var(--color-elevated-border)',
    borderRadius: 14,
    gap: 12,
    flexWrap: 'wrap',
  },
  projectInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    flex: 1,
    minWidth: 220,
  },
  projectHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  projectName: {
    fontWeight: 600,
  },
  activeBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '4px 8px',
    borderRadius: 999,
    background: 'var(--color-accent-soft)',
    color: 'var(--color-text)',
    fontSize: 12,
    fontWeight: 700,
  },
  projectMeta: {
    color: 'var(--color-text-muted)',
    fontSize: 13,
  },
  actions: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    borderRadius: 8,
    border: 'none',
    background: 'var(--color-accent)',
    color: 'white',
    fontSize: 13,
    cursor: 'pointer',
  },
  stopButton: {
    background: 'var(--color-danger)',
  },
  ghostButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    background: 'transparent',
    color: 'var(--color-text-muted)',
    fontSize: 13,
    cursor: 'pointer',
  },
  removeButton: {
    borderColor: 'var(--color-border)',
  },
  dangerButton: {
    background: 'var(--color-danger-strong)',
    color: 'white',
  },
}