import type { CSSProperties } from 'react'

export const focusDetailStyles: Record<string, CSSProperties> = {
  stopAction: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '12px 16px',
    borderRadius: 12,
    border: 'none',
    background: 'var(--color-danger)',
    color: 'white',
    fontWeight: 700,
    cursor: 'pointer',
  },
  primaryBlueAction: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '12px 16px',
    borderRadius: 12,
    border: 'none',
    background: 'var(--color-accent)',
    color: 'white',
    fontWeight: 700,
    cursor: 'pointer',
  },
  secondaryActionWide: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 14px',
    borderRadius: 12,
    border: '1px solid var(--color-border)',
    background: 'var(--color-input-bg)',
    color: 'var(--color-text)',
    cursor: 'pointer',
  },
  secondaryGhostAction: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: '12px 14px',
    borderRadius: 12,
    border: '1px solid var(--color-border)',
    background: 'transparent',
    color: 'var(--color-text)',
    cursor: 'pointer',
  },
  noteLabel: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  noteLabelText: {
    fontSize: 13,
    color: 'rgba(191, 219, 254, 0.82)',
    fontWeight: 600,
  },
  noteInput: {
    minHeight: 110,
    resize: 'vertical',
    padding: 12,
    borderRadius: 14,
    border: '1px solid rgba(96, 165, 250, 0.18)',
    background: 'rgba(15, 23, 42, 0.8)',
    color: 'var(--color-text)',
  },
  focusSide: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  miniStatCard: {
    padding: '16px 18px',
    borderRadius: 18,
    background: 'var(--color-panel)',
    border: '1px solid var(--color-elevated-border)',
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  miniStatLabel: {
    fontSize: 12,
    color: 'var(--color-text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  miniStatValue: {
    fontSize: 24,
    lineHeight: 1.1,
  },
  idleFocusCard: {
    padding: 24,
    borderRadius: 24,
    background: 'var(--color-panel)',
    border: '1px solid var(--color-elevated-border)',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    alignItems: 'flex-start',
  },
  idleFocusTitle: {
    margin: 0,
    fontSize: 28,
    lineHeight: 1.1,
  },
  idleFocusText: {
    margin: 0,
    color: 'rgba(148, 163, 184, 0.88)',
    maxWidth: 540,
  },
}