import type { CSSProperties } from 'react'

export const headerStyles: Record<string, CSSProperties> = {
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 16,
    flexWrap: 'wrap',
  },
  titleWrap: {
    maxWidth: 620,
  },
  eyebrow: {
    display: 'inline-block',
    marginBottom: 8,
    padding: '6px 10px',
    borderRadius: 999,
    background: 'var(--color-accent-soft)',
    color: 'var(--color-accent)',
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  title: {
    margin: 0,
    fontWeight: 700,
    lineHeight: 1.05,
  },
  subtitle: {
    margin: '10px 0 0',
    color: 'rgba(148, 163, 184, 0.88)',
    lineHeight: 1.6,
  },
  headerTools: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
  },
  headerChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 12px',
    borderRadius: 14,
    background: 'var(--color-panel)',
    border: '1px solid var(--color-elevated-border)',
    color: 'var(--color-text)',
  },
  headerChipLive: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 12px',
    borderRadius: 14,
    background: 'rgba(34, 197, 94, 0.12)',
    border: '1px solid rgba(34, 197, 94, 0.2)',
    color: '#bbf7d0',
  },
  notice: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    padding: '14px 16px',
    borderRadius: 14,
    border: '1px solid transparent',
  },
  noticeContent: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  },
  noticeError: {
    background: 'rgba(127, 29, 29, 0.45)',
    borderColor: 'rgba(248, 113, 113, 0.24)',
    color: 'var(--color-text)',
  },
  noticeInfo: {
    background: 'var(--color-panel-strong)',
    borderColor: 'var(--color-elevated-border)',
    color: 'var(--color-text)',
  },
  noticeDismiss: {
    padding: '8px 12px',
    borderRadius: 10,
    border: '1px solid var(--color-border)',
    background: 'transparent',
    color: 'var(--color-text-muted)',
    cursor: 'pointer',
  },
}