import type { CSSProperties } from 'react'

export const layoutStyles: Record<string, CSSProperties> = {
  layout: {
    minHeight: '100vh',
    width: '100%',
    maxWidth: 'none',
    margin: 0,
  },
  workspace: {
    display: 'grid',
    gridTemplateColumns: '76px minmax(0, 1fr)',
    gap: 24,
    alignItems: 'start',
  },
  rail: {
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
    alignItems: 'center',
    padding: '18px 8px',
    background: 'rgba(15, 23, 42, 0.86)',
    border: '1px solid var(--color-elevated-border)',
    boxShadow: 'var(--shadow-soft)',
  },
  railTop: {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
    paddingBottom: 10,
    borderBottom: '1px solid rgba(148, 163, 184, 0.14)',
  },
  brandMark: {
    width: 36,
    height: 36,
    borderRadius: 12,
    display: 'grid',
    placeItems: 'center',
    background: 'rgba(59, 130, 246, 0.14)',
    color: '#93c5fd',
    flexShrink: 0,
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    width: '100%',
    alignItems: 'center',
  },
  navButton: {
    width: 52,
    height: 52,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    borderRadius: 14,
    border: '1px solid transparent',
    background: 'transparent',
    color: 'var(--color-text)',
    cursor: 'pointer',
  },
  navIconWrap: {
    position: 'relative',
    width: 34,
    height: 34,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 12,
    background: 'rgba(51, 65, 85, 0.44)',
    flexShrink: 0,
  },
  liveDot: {
    position: 'absolute',
    right: 6,
    top: 6,
    width: 8,
    height: 8,
    borderRadius: 999,
    background: '#22c55e',
    boxShadow: '0 0 0 4px rgba(34, 197, 94, 0.16)',
  },
  railFooter: {
    marginTop: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  logoutRail: {
    width: 52,
    height: 52,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    borderRadius: 14,
    border: '1px solid var(--color-border)',
    background: 'transparent',
    color: 'var(--color-text-muted)',
    cursor: 'pointer',
  },
  contentStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
  },
}